language: python
python:
  - "3.4"
    #  - "pypy3"
cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/nltk_data
install:
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt --cache-dir $HOME/.pip-cache
  - python -m textblob.download_corpora
script:
  - py.test --cov=fewerror
  - flake8
after_success:
  - coveralls
before_deploy:
  - openssl aes-256-cbc -K $encrypted_bd9cd2af8138_key -iv $encrypted_bd9cd2af8138_iv -in ssh/id_rsa.enc -out ssh/id_rsa -d
  - chmod 600 ssh/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no -i ssh/id_rsa fewerror@gene.splice.org.uk /srv/fewerror/fewerror/update.sh $TRAVIS_COMMIT
  on:
    branch: master
